project:
  type: book
  output-dir: _book

book:
  title: "Authentication and Authorization in Web Applications"
  author: "Sridhar Ramachandran"
  date: "6/18/2026"
  sidebar:
    style: "docked"
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



